local totalMemory = computer.totalMemory()
local freeMemory = computer.freeMemory()
print("Total Memory: "..math.round(totalMemory / 1024).."Kb")
print("Used Memory: "..math.round((totalMemory - freeMemory)/1024).."Kb")
print("Free Memory: "..math.round(freeMemory/1024).."Kb")